### ISSUE TITLE
Some errors in sample

### ISSUE THREAD

**Issue by dmknght** [rgv151/ptrace.nim#3]
# System info
1. Parrot OS 4.9 (based on Debian testing)
2. Nim lang: 1.2.4 amd64
# Problems
I've tried ptrace lib by testing sample and i've found errors:
1. [Solved] Error at `import ptrace/ptrace`
Fix: edit it to `import ptrace`
2. [Solved] Error at `var child: Pid;` the `Pid` not found
Fix: add `import posix`
3. Error at `var regs = getRegs(child)`: Type mismatch, `child` is `pid` but expected of `getRegs(p: int, regs: ptr Registers)`.

**Comment by ba0f3** [comment]
Can you make a PR em?

**Comment by dmknght** [comment]
> Can you make a PR em?

sorry i don't understand :(

**Comment by ba0f3** [comment]
Can you fix it and make a pull request?

**Comment by dmknght** [comment]
okay let me check and create pull request :D
