### ISSUE TITLE
MacOSX: arm64, I am running the example and getting "22 Invalid argument".

### ISSUE THREAD

**Issue by treeform** [rgv151/ptrace.nim#4]
Just the example from the readme:
```nim
import posix, ptrace

var child: Pid;
var syscallNum: clong;

child = fork()
if child == 0:
  traceMe()
  discard execl("/bin/ls", "ls")
else:
  var a: cint
  wait(nil)

  var regs: Registers
  getRegs(child, addr regs)
  echo "Syscall number: ", regs.orig_rax
  if errno != 0:
    echo errno, " ", strerror(errno)

  syscallNum = peekUser(child, SYSCALL_NUM)
  if errno != 0:
    echo errno, " ", strerror(errno)
  echo "The child made a system call: ", syscallNum
  cont(child)
```

output:
```
Syscall number: 0
22 Invalid argument
22 Invalid argument
The child made a system call: -1
```

```
nim -v
Nim Compiler Version 1.7.1 [MacOSX: arm64]
Compiled at 2021-11-19
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: eb5358dcdb1b650db658def14cc8c60b4bb7c203
active boot switches: -d:release
```

**Comment by ba0f3** [comment]
AFAIK, SIP does not permit debug system binary

**Comment by treeform** [comment]
I want to trace my own binaries, i tried to use:

```nim
discard execl("/Users/me/p/hottie/examples/test3", "test3")
```
Still the same errors? 

Do I need to code sign it or some thing like that: https://timnash.co.uk/getting-gdb-to-semi-reliably-work-on-mojave-macos/?amp to get around the SIP?

Do you have ptrace working on mac?

Thanks!

**Comment by treeform** [comment]
I am trying to make hottie work on mac https://github.com/treeform/hottie .

**Comment by ba0f3** [comment]
it looks like mac does not support PTRACE_GETREGS request. I found this article may helps: http://uninformed.org/index.cgi?v=4&a=3&p=14

and `hottie` looks promise btw

**Comment by treeform** [comment]
Yeah I could not make any headway with ptrace. Doing `thread_get_state` call instead. This shows promise http://os-tres.net/blog/2010/02/17/mac-os-x-and-task-for-pid-mach-call/ but I had to adapt it to arm64 from x86.

Closing this now as I will probably not use ptrace on mac.
